### ISSUE TITLE
Matsu's messages sometimes repeat 

### ISSUE THREAD

**Issue by yonaymoris** [tommyquant/waiting-bot#3] opened 2019-08-02 08:18 UTC
Can you make matsu send a certain message only once? Seems like because of the randomized function sometimes it gets into the same message that was sent before.
<img width="413" alt="Screen Shot 2019-08-02 at 11 15 08 AM" src="https://user-images.githubusercontent.com/8845733/62355189-3172e780-b517-11e9-9e4e-d648ba003737.png">

**Comment by tommyquant** [comment] 2019-08-02 08:42
I can prevent matsu from repeating 'bad' messages by maintaining a list of already used 'bad' messages but matsu will eventually run out of messages to use. Should the list be cleared (so matsu can use the messages again) whenever matsu sends a 'good' message?

**Comment by yonaymoris** [comment] 2019-08-02 08:47
yes, that's what I mean
it's okay if the messages repeat in the "next session" of bad messages.

**Comment by tommyquant** [comment] 2019-08-02 09:23
matsu now doesn't repeat bad messages unless a good message has been sent. Let me know if it works as intended so I can close this issue.

Commit: https://github.com/tommyquant/waiting-bot/commit/4f593dbf659584769fec968ecadf90ad1f025895

**Comment by yonaymoris** [comment] 2019-08-02 09:31
It works fine now, thank you.

**Closed** 2019-08-02 09:31 UTC
Labels: enhancement
